### ISSUE TITLE
Back up + Restore

### ISSUE THREAD

**Issue by Anichiraku-Main** [YunoHost-Apps/baikal_ynh#42]
What is the best method for backing up all calendars and restoring them?

I'm trying to move my current Baikal install with several calendars into a new Yunohost install on a different domain.

**Comment by maniackcrudelis** [comment]
You can use the backup/restore feature of YunoHost, then the change_url feature to move to your new domain.

**Comment by D347HxD** [comment]
Awesome! Sounds easy.

Though, let's say on instance a (old one) I had the account named "thekore"
And on instance b (new one) the account is named "facinorous".

Would I backup and restore userdata as well to obtain the calendars to the correct user? If so, how would I make the calendars now accessible via the new account?

Please note the new instance has other apps that were not on instance a, so I'd prefer not to do a complete restore; only enough to get the Baikal transferred over so my AgenDAV can work with my old calendars

**Comment by maniackcrudelis** [comment]
You can bakup and restore baikal only, not the entire server.
I don't know how baikal handle its user, probably ldap, but for sure you won't get the data from another user. It have to be the same user names.

**Comment by D347HxD** [comment]
Would sharing the calendar be possible?
http://sabre.io/dav/caldav-sharing/

I'm trying to think of a work around since this new instance is based around a different account name. Maybe if I'm able to move the user and Calendar's by backing up Baikal + user-data in Yunohost then sharing the calendars/contact books/tasks with the new user, so all my old calendars will be viewable/usable on the new account?

Or am I pretty much better off copy-pasting all the calendar events into new calendars manually?

**Comment by maniackcrudelis** [comment]
I can't really help you on specific baikal features, as I'm not using that app.
For me, but it may have changed since, baikal doesn't allow to share calendars.

**Comment by HugoPoi** [comment]
@D347HxD I think sharing isn't the best option because if delete the old account you lose everything, in the past I used `vdirsyncer` to sync a old server account to my yunohost baikal.
https://vdirsyncer.pimutils.org/en/stable/tutorial.html
